all: enemy_test.o runall.o unity.o unity_fixture.o

enemy_test.o:
	gcc -c enemy_test.c -o ../build/enemy_test.o

runall.o:
	gcc -c runall.c -o ../build/runall.o

unity.o:
	gcc -c ../../unity/unity.c -o ../build/unity.o

unity_fixture.o:
	gcc -c ../../unity/unity_fixture.c -o ../build/unity_fixture.o
